### ISSUE TITLE
bug: Docs for nic module show usage of lan but there is no explanation 

### ISSUE THREAD

**Issue by hegerdes** [ionos-cloud/module-ansible#185] opened 2023-11-16 11:38 UTC
## Description

For the `ionoscloudsdk.ionoscloud.nic` module you show the usage of LAN. But in the Explination there is no entry for the LAN prob in state create.

<img width="599" alt="image" src="https://github.com/ionos-cloud/module-ansible/assets/40325561/0e52ba71-33cb-47ec-8baf-d6b72abe4891">

https://github.com/ionos-cloud/module-ansible/blob/de698cd2e7ff4cfcc4a147977329fd9f2e841f00/docs/api/compute-engine/nic.md?plain=1#L131-L234

## Expected behavior

Docs show all available parameters with explanation. Including `lan` of it is an option.

Question will the LAN be created if it is not existent when your create a NIC?

## Environment
Web

Ansible version:
```
Does not apply
```
Module version: 
```
v6.x & v7.x
```
OS: 
```
Web
```

**Comment by rmocanu-ionos** [comment] 2023-11-21 15:19
Hello,
There is an error in the docs, lan should be listed for the 'present' state as well, we will fix this in the following release. Thank you for helping us find the bug.
Regarding your question, the answer is no, the lan will not be created if it does not exist

**Comment by rmocanu-ionos** [comment] 2023-11-22 10:02
Thank you for bringing these points to our attention. We appreciate your patience as we work on aligning our examples with the actual module usage and ensuring all parameters are correctly indicated.

We will look into the discrepancy you've mentioned and update our documentation and examples accordingly.

Regarding the inconsistency you pointed out in the NIC module, I apologize for any confusion caused by my previous response. To clarify, Ansible itself does not directly create a LAN if it is not existent when creating a NIC. However, the underlying API does handle this by implicitly creating a LAN if it does not exist, both during the 'create' and 'update' states of a NIC. This behavior is consistent across these states, ensuring that the NIC is always associated with a valid LAN.

**Comment by hegerdes** [comment] 2023-11-22 12:15
Link #187

**Comment by rmocanu-ionos** [comment] 2023-12-11 15:39
Hello,

Regarding the DCD and API issues, these are not made and supported by us so we cannot offer an answer regarding how these work and if they will be changed. We have sent your feedback to the responsible teams. If you have any questions or more feedback related to the DCD, we encourage you to contact our support team directly by emailing support@cloud.ionos.com. This is the official and recommended communication channel to address DCD issues. This is a relatively new feature and we are happy for every feedback we receive.

The way IPV6 works right now is that you need a LAN with IPV6 enabled so the LAN should exist before creating the NIC. You can find more info about that here https://docs.ionos.com/cloud/compute/networks/ipv6.

Regarding the need to manually create a LAN with a certain ID (and not automatically via NIC creation) - that is not possible in the API at the moment. You can create a LAN without providing the ID and the API will generate one for it. 
Also, if you want, you can provide us more details about your desired setup and we can assist.

**Comment by rmocanu-ionos** [comment] 2023-12-21 15:09
Hello, I have merged the pull request containing the changes to the lan parameter on the nic module and also fixes to some examples. I will leave this issue open until we go through all the examples and update them. Thank you for signaling the issues to us. Happy holidays!

**Comment by hegerdes** [comment] 2024-01-03 10:11
This is great to hear and a welcoming change. However, this is no longer of any interests for me, as the planned project will not be pursued further, among other things due to the quality of IONOS services. 

I hope others will benefit from this.

**Comment by rmocanu-ionos** [comment] 2024-04-17 11:13
This should be solved in 7.4.1, please let us know if there are other issues.

**Closed by rmocanu-ionos** 2024-04-17 11:13 UTC
Labels: bug
