### ISSUE TITLE
Volume create 

### ISSUE THREAD

**Issue by gyokiss** [ionos-cloud/module-ansible#20] opened 2021-11-22 19:23 UTC
## Description
When I would like to create additional volume for newly created server, the ansible script runs though without error, but the volume is not present.

Additional volume is not created, the process is finished without any error message. 

## Expected behavior
volume is created

Ansible version:
ansible 2.10.15
  config file = None
  configured module search path = ['/usr/share/ansible/plugins/modules/ionos-module-ansible']
  ansible python module location = /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ansible
  executable location = /opt/rh/rh-python38/root/usr/local/bin/ansible
  python version = 3.8.11 (default, Sep  1 2021, 12:33:46) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]

Module version: 
5.0.5

OS: 
Centos7

## Configuration Files

ansible snipet: 

- name: Create data volume
  volume:
    username: "myusername"
    password: "password"
    datacenter: "{{ datacenter }}"
    server: "{{ machines[0].id }}"
    size: 10
    disk_type: HDD
    name: "backupdisk"
    licence_type: "OTHER"
    wait_timeout: "{{ timeout }}"
    availability_zone: ZONE_1
    state: present 
  environment: "{{ proxy_env }}"
#    ignore_errors: yes
 tags: always
  delegate_to: localhost

## Error and Debug Output
ok: [localhost -> localhost] => {
    "action": "create",
    "changed": false,
    "instance_ids": [],
    "invocation": {
        "module_args": {
            "api_url": null,
            "auto_increment": true,
            "availability_zone": "ZONE_1",
            "backupunit_id": null,
            "bus": "VIRTIO",
            "count": 1,
            "cpu_hot_plug": null,
            "datacenter": "datcenterID",
            "disc_virtio_hot_plug": null,
            "disc_virtio_hot_unplug": null,
            "disk_type": "HDD",
            "image": null,
            "image_password": null,
            "instance_ids": [],
            "licence_type": "OTHER",
            "location": null,
            "name": "backupdisk",
            "nic_hot_plug": null,
            "nic_hot_unplug": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ram_hot_plug": null,
            "server": "serverID",
            "size": 10,
            "ssh_keys": [],
            "state": "present",
            "user_data": null,
            "username": "myusername",
            "wait": true,
            "wait_timeout": 600
        }
    },
    "volumes": []
}

**Comment by mihaela-mh** [comment] 2021-11-23 09:24
Hello! 

Can you, please, provide the entire playbook? _(Or at least the part with the creation of the first module)_ 
I am asking because the Ansible module skips the volume creation if a volume with the same name already exists, so this would be a reason for the described behavior. If the volumes have different names, a more detailed playbook would be helpful for reproducing the problem.

Thank you!

**Comment by gyokiss** [comment] 2021-11-23 09:57
Hi,

the the required snipet is the first volume creation. (  The server does not have named volume before).
I have found the "interesting berhavior: if I name the new volume: datadisk or backupdisk it failes, but it the name has number on end: datadisk0 datadisk1, backupdisk0. etc it runs fine... 

Gyorgy

**Comment by mihaela-mh** [comment] 2021-12-15 12:06
Hello!

Thank you for the provided info. We're currently working on the fix for this bug. I've been trying to reproduce the scenario you presented, but with no success. Can you, please, provide more information about the setup? It would be helpful to have more details about the server (location, other entities, etc.), and I think the easier way to do that would be to provide here the command you use for the creation of the server _(with sensitive info covered, of course)_.

Thank you!

**Comment by mihaela-mh** [comment] 2021-12-15 12:23
Update: I receive the same output as above only if I try to create a volume that already exists. The empty list (`"volumes": []`) on response appears due to another issue whose fix will be included in the next release.
Can you, please, check on the API level or on DCD and confirm that, after running the playbook, the volume is not created?

**Comment by rmocanu-ionos** [comment] 2024-03-05 10:13
Closing this issue due to inactivity. If the problem persists or you have new info, please open a new issue and link back to this one. Thanks!

**Closed by rmocanu-ionos** 2024-03-05 10:13 UTC
Labels: bug
